const ACCOUNT_CREATION_LOADING_TEXTS = [
  "Adding Hidden Agendas",
  "Adjusting Bell Curves",
  "Aesthesizing Industrial Areas",
  "Aligning Covariance Matrices",
  "Applying Feng Shui Shaders",
  "Applying Theatre Soda Layer",
  "Asserting Packed Exemplars",
  "Attempting to Lock Back-Buffer",
  "Binding Sapling Root System",
  "Breeding Fauna",
  "Building Data Trees",
  "Bureacritizing Bureaucracies",
  "Calibrating Blue Skies",
  "Charging Ozone Layer",
  "Coalescing Cloud Formations",
  "Cohorting Exemplars",
  "Collecting Meteor Particles",
  "Compounding Inert Tessellations",
  "Compressing Fish Files",
  "Computing Optimal Bin Packing",
  "Concatenating Sub-Contractors",
  "Containing Existential Buffer",
  "Debarking Ark Ramp",
  "Decomposing Singular Values",
  "Decrementing Tectonic Plates",
  "Deleting Ferry Routes",
  "Depositing Slush Funds",
  "Destabilizing Economic Indicators",
  "Determining Width of Blast Fronts",
  "Deunionizing Bulldozers",
  "Dicing Models",
  "Extracting Resources",
  "Factoring Pay Scale",
  "Fixing Election Outcome Matrix",
  "Flood-Filling Ground Water",
  "Flushing Pipe Network",
  "Gathering Particle Sources",
  "Generating Jobs",
  "Gesticulating Mimes",
  "Graphing Whale Migration",
  "Hiding Willio Webnet Mask",
  "Implementing Impeachment Routine",
  "Increasing Magmafacation",
  "Inserting Sublimated Messages",
  "Integrating Curves",
  "Integrating Population Graphs",
  "Iterating Cellular Automata",
  "Lecturing Errant Subsystems",
  "Mixing Genetic Pool",
  "Modeling Object Components",
  "Mopping Occupant Leaks",
  "Normalizing Power",
  "Obfuscating Quigley Matrix",
  "Perturbing Matrices",
  "Pixalating Nude Patch",
  "Polishing Water Highlights",
  "Populating Lot Templates",
  "Preparing Sprites for Random Walks",
  "Prioritizing Landmarks",
  "Realigning Alternate Time Frames",
  "Relaxing Splines",
  "Removing Texture Gradients",
  "Resolving GUID Conflict",
  "Reticulating Splines",
  "Retracting Phong Shader",
  "Retrieving from Back Store",
  "Scattering Rhino Food Sources",
  "Scrubbing Terrain",
  "Searching for Llamas",
  "Sequencing Particles",
  "Setting Advisor Moods",
  "Setting Inner Deity Indicators",
  "Setting Universal Physical Constants",
  "Speculating Stock Market Indices",
  "Splatting Transforms",
  "Stratifying Ground Layers",
  "Sub-Sampling Water Data",
  "Synthesizing Gravity",
  "Synthesizing Wavelets",
  "Time-Compressing Simulator Clock",
  "Unable to Reveal Current Activity",
  "Weathering Buildings",
  "Zeroing Crime Network"
];

export {ACCOUNT_CREATION_LOADING_TEXTS};
