import ROUTES from "../../../../core/route/routes";

const AVAILABLE_PAGE_HEADER_GO_BACK_ROUTES = [
  ROUTES.ACCOUNT.ROUTE,
  ROUTES.ACCOUNT.CREATE.FULL_PATH,
  ROUTES.ACCOUNT.IMPORT.PASSPHRASE.FULL_PATH,
  ROUTES.ACCOUNT.IMPORT.PASSPHRASE.NAME.FULL_PATH,
  ROUTES.ACCOUNT.IMPORT.PASSPHRASE.RECOVERY.FULL_PATH,
  ROUTES.ACCOUNT.IMPORT.PERA_SYNC.FULL_PATH,
  ROUTES.ACCOUNT.IMPORT.PERA_SYNC.QR.FULL_PATH,
  ROUTES.PASSWORD.CREATE.FULL_PATH,
  ROUTES.ASSET_OPTIN.ROUTE,
  ROUTES.ASSET_OPTIN.ACCOUNTS.FULL_PATH
];

export {AVAILABLE_PAGE_HEADER_GO_BACK_ROUTES};
